on:
  pull_request:
    branches:
      - master

name: Test and Coverage

jobs:
  testing:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Generate coverage report
        run: npm run coverage
      - name: Publish coverage report
        uses: actions/upload-artifact@v2
        with:
          path: coverage/lcov.info
          name: code-coverage
  coverage_report:
    name: Generate coverage report
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download code coverage from GitHub
        uses: actions/download-artifact@v2
        with:
          name: code-coverage
          path: coverage
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GH_TOKEN }}
